### PR TITLE
Text selection fix

### PR DESCRIPTION
**Pull request by finallyblueskies**
This PR adds a view that renders chat messages by:

- Converting the LLM chat response into HTML using libcmark_gfm.
- Displaying the HTML in a WKWebView.

This implementation enables free text selection, thereby resolving https://github.com/psugihara/FreeChat/issues/22.

This is my first open-source PR and it's also my first time working with SwiftUI. I would greatly appreciate any suggestions for tackling the above problem, as well as for improving the code or anything else.

To-do list:

- [x] Resolve the initial message sizing issue.
- [x] Fix the resizing issue for messages.
- [ ] Ensure previous styling & theme.
- [ ] Reimplement codeblocks.
- [ ] Connect message functions (copy message, more details etc.) back to Swift
- [ ] Ensure new messages render properly as they stream

### CODE REVIEW

**Comment by finallyblueskies** [comment]
Doing some testing, even with a fixed height to simulate precalculated dimensions there is a flash of unstyled content. It seems that most of the overhead is parsing and rendering markdown into HTML, noticeable even on my M3:

https://github.com/psugihara/FreeChat/assets/14274086/4d349a51-1609-4730-a3c9-ee78bb3a9571

I think that the only way this approach would move forward is if:
- @psugihara is OK with the drop in responsiveness as the cost for free text selection - perhaps this can be masked, such as an animation to to fade in the views once content is rendered? Might look pleasing while feeling almost as responsive as the previous approach
- A more efficient MD to WKWebView rendering approach is used. No sure what that would be atm

**Comment by psugihara** [comment]
> @psugihara is OK with the drop in responsiveness as the cost for free text selection - perhaps this can be masked, such as an animation to to fade in the views once content is rendered? Might look pleasing while feeling almost as responsive as the previous approach

yeah that seem ok to me if we can get the styles aligned exactly. nice work so far, excited to dig into the diff a bit more.

**Comment by finallyblueskies** [comment]
Exploring native solutions I found that to implement more complex visual elements like tables, code blocks, or images in SwiftUI, it becomes challenging because the framework doesn't support selection across different views easily. As a result, I doubled down on a WKWebView, enabling the entire conversation thread to be rendered using HTML and CSS. This approach introduces an intermediate layer between the conversation view and the app's other components, requiring a bridge between the web view’s event handling and SwiftUI.

For instance, showing a menu in the traditional way involved simple Swift code:

```swift
Menu(content: {
    menuContent
},
// ... menu config
```
      
Showing that same menu from the web view requires:

Registering the action with a WKUserContentController:
```swift
    let userContentController = WKUserContentController()
    userContentController.add(context.coordinator, name: "displayMenu")
    
    let webViewConfiguration = WKWebViewConfiguration()
    webViewConfiguration.userContentController = userContentController
    
    let webView = WKWebView(frame: .zero, configuration: webViewConfiguration)
```
Defining callback handlers:

```swift
func userContentController(_ userContentController: WKUserContentController, didReceive message: WKScriptMessage) {
  if message.name == "displayMenu" {
    displayMenu(webView: webView!)
  }
}

func displayMenu(webView: WKWebView) {
  let menu = NSMenu()
  menu.addItem(NSMenuItem(title: "Option 1", action: #selector(optionSelected(_:)), keyEquivalent: ""))
  menu.addItem(NSMenuItem(title: "Option 2", action: #selector(optionSelected(_:)), keyEquivalent: ""))
  NSMenu.popUpContextMenu(menu, with: NSApp.currentEvent!, for: webView)
}
```

Defining the button in HTML:

```html
<button class="menu-button">
    ...
<button>
```

Connecting it all together:

```javascript
document.querySelector(".menu-button").addEventListener("click", (e) => {
  window.webkit.messageHandlers.displayMenu.postMessage({
      //...
  });
})
```

This method, while complex, offers significant advantages:

- Entire conversations are selectable.
- Full control over the style and behavior of any HTML content.
- Improved rendering performance, possibly due to more efficient layout processes, which I observed as noticeably faster.

You can observe the interaction in the video below, where the left side is current FreeChat main:

https://github.com/psugihara/FreeChat/assets/14274086/100968c9-ef2a-4b70-b737-eba051df662b

I understand this is a pretty opinionated approach, I will merge it for my FreeChat fork, @psugihara let me know if you're OK with it for FreeChat, in which case I will keep this PR open and complete it here.

**Comment by finallyblueskies** [comment]
Further exploration of a HTML rendering approach has led me to understand that rendering the whole conversation in HTML makes for a nice, fast prototype but quickly becomes very complex when we need to start re-introducing previous UI elements, functionality and actually efficient rendering. A whole SwiftUI <-> WKWebView API starts to take shape, with lots of duplication and indirection, and while this is a fun exercise it is a completely overblown solution to the problem of having freely selectable messages. I am closing this PR in favor of https://github.com/psugihara/FreeChat/pull/65

**Pull request closed without merging**
