### PR TITLE
Allow for gguf selection and multiple imports

### PR DESCRIPTION
**Pull request by shavit**
This change will allow import of only `.gguf` files, however it will not dismiss the settings window. Maybe users want to manage their models and not start a conversation right away.

Closes https://github.com/psugihara/FreeChat/issues/35

### CODE REVIEW

**Comment by psugihara** [comment]
Editing the issue for clarity.

**Comment by shavit** [comment]
Got it. I'll need to look into appDelegate and handling multiple windows, since in my branch dropping a file opens a new window. Multiple windows will also be necessary for private chat, or maybe using multiple models.

**Comment by psugihara** [comment]
Thanks for taking another look, excited about this feature!

Probably I'm misunderstanding but I don't think we need multiple windows. I only want one model and one instance of llama server etc to run at a time.

> private chat

If you're referring to #7, I imagine this working like any other conversation (in the same window) except that nothing is persisted to Core Data.

**Comment by shavit** [comment]
Yes, you're right.

**Pull request merged**
